name: Multi-Subscription AKS Health Check

on:
  schedule:
    - cron: "*/15 * * * *"   # Every 15 minutes (UTC)
  workflow_dispatch:

jobs:
  aks-health:
    runs-on: ubuntu-latest

    steps:
      ############################################################
      # CHECKOUT REPOSITORY
      ############################################################
      - name: Checkout repository
        uses: actions/checkout@v4

      ############################################################
      # LOGIN TO AZURE (SERVICE PRINCIPAL VIA AZURE_CREDENTIALS)
      ############################################################
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      ############################################################
      # INSTALL REQUIRED TOOLS
      ############################################################
      - name: Install kubectl, jq
        run: |
          sudo az aks install-cli
          sudo apt-get update -y
          sudo apt-get install -y jq

      ############################################################
      # RUN AKS HEALTH SCRIPT
      ############################################################
      - name: Run AKS Multi-Subscription Health Scan
        run: |
          chmod +x scripts/aks_health_all_subs.sh
          ./scripts/aks_health_all_subs.sh

      ############################################################
      # UPLOAD HTML REPORT TO AZURE STORAGE (NO OVERWRITE)
      ############################################################
      - name: Upload HTML Report to Azure Storage
        id: upload
        run: |
          echo "Ensuring container exists..."
          az storage container create \
            --name "${{ secrets.AZURE_STORAGE_CONTAINER }}" \
            --account-name "${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}" \
            --account-key "${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}"

          TS=$(date +"%Y-%m-%d-%H-%M")
          REPORT_NAME="AKS-Health-Report-${TS}.html"

          echo "Uploading report: ${REPORT_NAME}"

          az storage blob upload \
            --container-name "${{ secrets.AZURE_STORAGE_CONTAINER }}" \
            --account-name "${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}" \
            --account-key "${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}" \
            --file "reports/AKS Cluster Health.html" \
            --name "${REPORT_NAME}" \
            --overwrite false

          echo "report_name=${REPORT_NAME}" >> "$GITHUB_OUTPUT"

      ############################################################
      # GENERATE SAS URL (READ-ONLY, 3 DAYS)
      ############################################################
      - name: Generate SAS URL for HTML Report
        id: sas
        run: |
          EXPIRY=$(date -u -d "3 days" '+%Y-%m-%dT%H:%MZ')

          TOKEN=$(az storage blob generate-sas \
            --account-name "${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}" \
            --account-key "${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}" \
            --container-name "${{ secrets.AZURE_STORAGE_CONTAINER }}" \
            --name "${{ steps.upload.outputs.report_name }}" \
            --permissions r \
            --expiry "$EXPIRY" \
            -o tsv)

          SAS_URL="https://${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}.blob.core.windows.net/${{ secrets.AZURE_STORAGE_CONTAINER }}/${{ steps.upload.outputs.report_name }}?${TOKEN}"

          echo "sasurl=${SAS_URL}" >> "$GITHUB_OUTPUT"

      ############################################################
      # DISPLAY FINAL OUTPUT
      ############################################################
      - name: Show Report URL
        run: |
          echo "================================================="
          echo " AKS HEALTH REPORT GENERATED"
          echo " File  : ${{ steps.upload.outputs.report_name }}"
          echo " URL   : ${{ steps.sas.outputs.sasurl }}"
          echo "================================================="
